import sys 
import os 
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt 
import geopandas 

import pyemu
from pymarthe import * 

# load Marthe model
mm = MartheModel('./mona.rma')
nlay, nrow, ncol = mm.nlay, mm.nrow, mm.ncol

# ---------------------------------------------------------------
# Load geometry and identify confined/unconfined domains
# ---------------------------------------------------------------
# see previous version of pst_setup to update these files if necessary
x, y, confined  = marthe_utils.read_grid_file(mm.mlname+'.conf')
x, y, unconfined  = marthe_utils.read_grid_file(mm.mlname+'.unconf')

# ---------------------------------------------------------------
# -------- STEP 2 : import prior data from excel file -----------
# ---------------------------------------------------------------

# set initial values
xls = pd.ExcelFile('./param.xlsx')
column_names = ['lay', 'parlbnd', 'parubnd','parval1']

# read prior data of each param dfrom param.xlsx as a dataframe
# assign new columns names and add a new column with the param name (assign)
df_kepon = pd.read_excel(xls, 'kepon', names= column_names,index_name   = 'kepon').assign(parname='kepon')
df_permh = pd.read_excel(xls, 'permh', names= column_names).assign(parname = 'permh')
df_Ss = pd.read_excel(xls, 'Ss', names= column_names).assign(parname = 'emmca')
df_w  = pd.read_excel(xls, 'w', names= column_names).assign(parname = 'emmli')

#Concatenate all the param dataframes 
prior_data_df = pd.concat([df_Ss,df_w,df_permh,df_kepon])

# set parameter name and layer as indexes
prior_data_df.set_index(['parname','lay'],inplace=True)

# --------------------------------------------------------------
# -------- clear folder  -----------
# --------------------------------------------------------------

# path to output folders 
tpl_dir = os.path.join('.','tpl')
par_dir = os.path.join('.','param')
ins_dir = os.path.join('.','ins')
sim_dir = os.path.join('.','sim')

# clear output folders
l = [ os.remove(os.path.join(tpl_dir,f)) for f in os.listdir(tpl_dir) if f.endswith(".tpl") ]
l = [ os.remove(os.path.join(par_dir,f)) for f in os.listdir(par_dir) if f.endswith(".dat") ]
l = [ os.remove(os.path.join(ins_dir,f)) for f in os.listdir(ins_dir) if f.endswith(".ins") ]

# --------------------------------------------------------------
# ------------------- parameter settings  ----------------------
# --------------------------------------------------------------

# log-transformation 
log_transform_dic = {'kepon': True,'permh': True,'emmca' : True,'emmli': False}

# ---------  set up izones dictionary  --------
# reload if necessary
#x, y, confined  = marthe_utils.read_grid_file(mm.mlname+'.conf')
#x, y, unconfined  = marthe_utils.read_grid_file(mm.mlname+'.unconf')

# only in confined zone for emmca and first layer with ZPC 
izone_emmca = np.zeros( (nlay, nrow, ncol) )
izone_emmca[ confined ] = 1
izone_emmca[0,:,:] = -1

# everywhere for permh
izone_permh = np.ones( (nlay, nrow, ncol) ) 

# -1 or zpc :
izone_zpc = -1*np.ones( (nlay, nrow, ncol) )

# izone dic set to none for default values (layer-based ZPC)
izone_dic = {'emmca':izone_emmca , 'permh':izone_permh,'kepon': izone_zpc,'emmli': izone_zpc}

# set up pilot point spacings with pp_ncells
pp_ncells_dic = {}
for par in izone_dic.keys():
    pp_ncells_dic[par] = {}
    for lay in range(0,11) : 
        pp_ncells_dic[par][lay] = 18
    for lay in range(11,nlay) : 
        pp_ncells_dic[par][lay] = 18

# get observation locations for pilot point adaptive refinement 
df_histo = marthe_utils.read_histo_file('mona.histo')

# setup template files 
# iterate over parameters with izone data  
for par in izone_dic.keys():
    print('Processing parameter {0}...'.format(par))
    # add parameter 
    mm.add_param(par, izone = izone_dic[par], default_value = 1e-5, log_transform=log_transform_dic[par])
    # write izone to disk for future use by model_run
    marthe_utils.write_grid_file('{0}.i{1}'.format(mm.mlname,par),mm.x_vals,mm.y_vals,izone_dic[par])
    # parameters with pilot points (izone with positive values)
    if np.max(np.unique(izone_dic[par])) > 0  :
        print('Setting up pilot points for parameter {0}'.format(par))
        # iterate over layers 
        for lay in range(mm.nlay):
            # layers with pilot points (izone with positive values)
            if np.max(np.unique(izone_dic[par][lay,:,:])) > 0 :
                # layer-dependent variogram settings
                mm.param[par].pp_from_rgrid(lay, n_cell=pp_ncells_dic[par][lay], n_cell_buffer = True)
                # pointer to pilot point dataframe generated by pp_from_rgrid
                pp_df = mm.param[par].pp_dic[lay]
                print('{0} pilot points seeded for parameter {1}, layer {2}'.format(pp_df.shape[0],par,lay+1))
                # refine pilot point grid where observations are dense
                loc_df = df_histo.loc[df_histo['layer'] == lay+1]
                df = mm.param[par].get_pp_nobs(lay, loc_df)
                df['refine'] = df['nobs'] > 2 # current criteria
                mm.param[par].pp_refine(lay,df)
                # desired variogram range (3 times pilot base point spacing)
                vario_range = 3*mm.cell_size*pp_ncells_dic[par][lay]
                # variogram setup :
                #   - parameter a is considered as a proxy for range
                #   - the contribution has no effect
                v = pyemu.utils.ExpVario(contribution=1, a=vario_range)
                # build up GeoStruct
                gs = pyemu.utils.GeoStruct(variograms=v,transform="log")
                # get covariance matrix 
                mm.param[par].ppcov_dic[lay] = gs.covariance_matrix(pp_df.x,pp_df.y,pp_df.name)
                # set up kriging
                ok = pyemu.utils.OrdinaryKrige(geostruct=gs,point_data=pp_df)
                # spatial reference (for pyemu compatibility only)
                ok.spatial_reference = SpatialReference(mm) 
                # pandas dataframe of point where interpolation shall be conducted
                # set up index for current zone and lay
                x_coords, y_coords = mm.param[par].zone_interp_coords(lay,zone=1)
                # compute kriging factors
                #kfac_df = ok.calc_factors(x_coords, y_coords,pt_zone=1, num_threads=4)
                # write kriging factors to file
                kfac_file = os.path.join(mm.mldir,'kfac_{0}_l{1:02d}.dat'.format(par,lay+1))
                #ok.to_grid_factors_file(kfac_file)
        # write initial parameter value file (all zones)
        mm.param[par].write_pp_df()
        mm.param[par].write_pp_tpl()
    # set up ZPCs if present
    # will have not effect for parameters and layers with pilot points
    mm.param[par].write_zpc_data()
    mm.param[par].write_zpc_tpl()

# --------------------------------------------------------------
# --------- testing pp refinement adaptive to obs density  -------------
# --------------------------------------------------------------


par = 'permh'
lay = 6
loc_df = df_histo.loc[df_histo['layer'] == lay]
df = mm.param[par].get_pp_nobs(lay,loc_df)
df['refine'] = df['nobs'] > 4
mm.param[par].pp_refine(lay,df)

df = mm.param[par].get_pp_nobs(lay,loc_df)
df['refine'] = df['nobs'] > 4
mm.param[par].pp_refine(lay,df)

ax = mm.param[par].pp_dic[lay].plot.scatter('x','y')
loc_df = df_histo.loc[df_histo['layer'] == lay]
ax.plot(loc_df['x'],loc_df['y'],'r+')
ax.set_aspect('equal')
# --------------------------------------------------------------
# -------------------- observations set up   ---------------------
# --------------------------------------------------------------

# --- Observations ---
# observation files (generated by obs_pproc.py)
obs_dir = os.path.join(mm.mldir,'obs','')

# NOTE : added sorted() to match with sorted list of sim files
obs_files = [os.path.join(obs_dir, f) for f in sorted(os.listdir( obs_dir )) if f.endswith('.dat')]

# add observations
for obs_file in obs_files :
    mm.add_obs(obs_file = obs_file)

# write instruction files
for obs_loc in mm.obs.keys() :
    mm.obs[obs_loc].write_ins()

# -------------------------------------------------------------
# -------------- STEP 3: setup PEST control file  -------------
# -------------------------------------------------------------

# -------------- list files ------------------------------------

# template files
tpl_files = [os.path.join(tpl_dir, f) for f in sorted(os.listdir( tpl_dir )) if f.endswith('.tpl')]

# input parameter files 
par_files = [os.path.join(par_dir, f) for f in sorted(os.listdir( par_dir )) if f.endswith('.dat')]

# instruction files 
ins_files = [os.path.join(ins_dir, f) for f in sorted(os.listdir( ins_dir )) if f.endswith('.ins')]

# output simulation files 
sim_files = [os.path.join(sim_dir, f + '.dat') for f in sorted(list(mm.obs.keys()))  ]

# --------------------- set up pst file -----------------------------
pst = pyemu.helpers.pst_from_io_files(tpl_files, par_files, ins_files, sim_files)


# set observation values and weights in the pst
for obs_loc in list(mm.obs.keys()):
    pst.observation_data.loc[mm.obs[obs_loc].df.index,'obsval'] = mm.obs[obs_loc].df.value
    pst.observation_data.loc[mm.obs[obs_loc].df.index,'weight'] = mm.obs[obs_loc].df.weight
    pst.observation_data.loc[mm.obs[obs_loc].df.index,'obgnme'] = obs_loc

# initialize values (initial and boundary values)
for stat in ['parlbnd','parval1','parubnd']:
    for par in izone_dic.keys() :
        # ZPCs : iterate over ZPCs in zpc_df
        for parname in mm.param[par].zpc_df.index :
            # set parameter group
            pst.parameter_data.loc[ parname , 'pargp'] = par
            # get value from prior data 
            lay = mm.param[par].zpc_df.loc[parname,'lay']
            val = prior_data_df.loc[(par,lay+1),stat]
            # log-transform values when necessary
            # and write to PEST
            if log_transform_dic[par] == True : 
                pst.parameter_data.loc[ parname , stat] = np.log10(val)
            else : 
                pst.parameter_data.loc[ parname , stat] = val
        # pilot points :iterate over layers with pilot points
        for lay in mm.param[par].pp_dic.keys() :
            # iterate over pp_df for given layer 
            for parname in mm.param[par].pp_dic[lay].index :
                pst.parameter_data.loc[ parname , 'pargp'] = par
                # get value from prior data 
                val = prior_data_df.loc[(par,lay+1),stat]
                # log-transform values when necessary
                # and write to PEST
                if log_transform_dic[par] == True : 
                    pst.parameter_data.loc[ parname , stat] = np.log10(val)
                else : 
                    pst.parameter_data.loc[ parname , stat] = val


# set parameter transformation to none (log-transformation handled by PyMarthe)
pst.parameter_data.loc[:,'partrans'] = 'none'

# set parameter change limit to relative (factor not accepted va
pst.parameter_data.loc[:,'parchglim'] = 'relative'

# further settings (with log-transformed values) 
pst.parameter_data.loc[ pst.parameter_data['pargp'] == 'emmca' , 'parubnd'] =  2
pst.parameter_data.loc[ pst.parameter_data['pargp'] == 'emmli' , 'parubnd'] =  1
pst.parameter_data.loc[ pst.parameter_data['pargp'] == 'permh' , 'parubnd'] =  2
pst.parameter_data.loc[ pst.parameter_data['pargp'] == 'kepon' , 'parubnd'] =  2

pst.parameter_data.loc[ pst.parameter_data['pargp'] == 'kepon' , 'parlbnd'] =  -20
pst.parameter_data.loc[ pst.parameter_data['pargp'] == 'permh' , 'parlbnd'] =  -20
pst.parameter_data.loc[ pst.parameter_data['pargp'] == 'emmca' , 'parlbnd'] =  -20
pst.parameter_data.loc[ pst.parameter_data['pargp'] == 'emmli' , 'parlbnd'] =  -20

# fix insensitive parameters 
pst.parameter_data.loc['kepon_l01_zpc01','partrans'] = 'fixed'
pst.parameter_data.loc['emmca_l01_zpc01','partrans'] = 'fixed'

# update parameter_groups from parameter_data 
pst.rectify_pgroups()

# Zero-order Tikhonov reg
pyemu.helpers.zero_order_tikhonov(pst)

# First-order Tikhonov reg for pilot points
for par in izone_dic.keys() :
    for lay in mm.param[par].ppcov_dic.keys() :
        cov_mat = mm.param[par].ppcov_dic[lay]
        pyemu.helpers.first_order_pearson_tikhonov(pst,cov_mat,reset=False,abs_drop_tol=0.2)


# derivative calculation type 
pst.parameter_groups.loc[ pst.parameter_groups.index,'forcen'] = 'always_3'
pst.parameter_groups.loc[ pst.parameter_groups.index,'inctyp'] = 'absolute'
pst.parameter_groups.loc[ pst.parameter_groups.index,'derinc'] = 0.15
pst.parameter_groups.loc[ pst.parameter_groups.index,'derincmul'] = 1.0

# pestpp-glm options 
pst.pestpp_options['svd_pack'] = 'propack'
pst.pestpp_options['lambdas'] = str(list(np.power(10,np.linspace(-2,3,6)))).strip('[]')
pst.pestpp_options['lambda_scale_fac'] = str(list(np.power(10,np.linspace(-2,0,12)))).strip('[]')

pst.control_data.jcosaveitn

# write pst 
pst.write('calreg_test2.pst')

