import sys 
import os 
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt 
import geopandas 

sys.path.append('/Users/apryet/Programmes/python/pyemu/')
import pyemu

sys.path.append('/Users/apryet/Programmes/python/adeqwat')
from pymarthe import * 

# ------- STEP 1 : setup
# load existing Marthe model
mm = MartheModel('/Users/apryet/recherche/adeqwat/dev/adeqwat/MONA_V3/mona.rma')

# -- parameters

# add new parameter
mm.add_param('kepon',1e-3)

for parname in list(mm.param.keys()):
    mm.param[parname].write_zpc_tpl()

mm.param['kepon'].write_zpc_data()
# -- observations

# observation files (generated by obs_pproc.py)
obs_dir = os.path.join(mm.mldir,'obs','')
obs_files = [os.path.join(obs_dir, f) for f in os.listdir( obs_dir ) if f.endswith(".txt")]

# add observations
for obs_file in obs_files :
    mm.add_obs(obs_file = obs_file)

# write instruction files
for obs_loc in mm.obs.keys() : 
    mm.obs[obs_loc].write_ins()

# -- PEST files

# template files
tpl_dir = os.path.join('.','tpl')
tpl_files = [os.path.join(tpl_dir, f) for f in os.listdir( tpl_dir ) if f.endswith(".tpl")]

# input parameter files 
par_dir = os.path.join('.','param')
par_files = [os.path.join(par_dir, f) for f in os.listdir( par_dir ) if f.endswith(".dat")]

# instruction files 
ins_dir = os.path.join('.','ins')
ins_files = [os.path.join(ins_dir, f) for f in os.listdir( ins_dir ) if f.endswith(".ins")]

# output simulation files 
sim_dir = os.path.join('.','sim')
sim_files = [os.path.join(sim_dir, f) for f in os.listdir( sim_dir ) if f.endswith(".dat")]

sim_files = [sim_files[0]]

# set up pst file
pst = pyemu.helpers.pst_from_io_files(tpl_files, par_files, ins_files, sim_files)


# set observation values and weights in the pst
for obs_loc in list(mm.obs.keys()):
    pst.observation_data.loc[mm.obs[obs_loc].df.index,'obsval'] = mm.obs[obs_loc].df.value
    pst.observation_data.loc[mm.obs[obs_loc].df.index,'weight'] = mm.obs[obs_loc].df.weight
    pst.observation_data.loc[mm.obs[obs_loc].df.index,'obgnme'] = obs_loc

# temporary trick
mm.param['kepon'].zpc_df['value'] = 1e-6

# set parameter value and group
for param in list(mm.param.keys()):
    pst.parameter_data.loc[ mm.param[param].zpc_df.index , "parval1"] = mm.param['kepon'].zpc_df.value
    pst.parameter_data.loc[ mm.param[param].zpc_df.index , "pargp"] = param

pst.write(mm.mlname + '.pst')
# ------- STEP 2 : use

mm = MartheModel('/Users/apryet/recherche/adeqwat/dev/adeqwat/MONA_V3/mona.rma')

# -- parameter
mm.add_parameter('kepon',1e-3)

# load zpc parameter values from file
kepon.read_zpc_df()

# set parameter array
kepon.set_array_from_zpc_df()

# -- model run

# -- load simulation

# extract prn
mm.extract_prn()

